const materials = [{
    name: "PBR PLASTIC",
    img: ["pbrplastic.png"],
    file: "PBRPlastic.blend",
    size: 0.47,
    blender: "2.7x",
    engine: "Cycles",
    author: "Retrax",
    pub: "July 13, 2020",
    lic: "CC0 1.0 Universal",
    desc: "A simple PBR plastic shader."
}, {
    name: "CUTTING MAT",
    img: ["cuttingmat.png"],
    file: "CuttingMat.blend",
    size: 0.53,
    author: "Retrax",
    blender: "2.7x",
    engine: "Cycles",
    pub: "July 13, 2020",
    lic: "CC0 1.0 Universal",
    desc: "A shader designed to emulate the surface of a cutting mat which is often used in workshop."
}, {
    name: "FLANNEL",
    img: ["flannel.png"],
    file: "Flannel.blend",
    size: 0.60,
    author: "Nanoman",
    blender: "2.7x",
    engine: "Cycles",
    pub: "July 13, 2020",
    lic: "CC0 1.0 Universal",
    desc: "A shader designed to emulate the surface of flannel clothing."
}, {
    name: "GRAINY PLASTIC",
    img: ["grainyplastic.png"],
    file: "GrainyPlastic.blend",
    size: 0.47,
    author: "Retrax",
    blender: "2.7x",
    engine: "Cycles",
    pub: "July 14, 2020",
    lic: "CC0 1.0 Universal",
    desc: "A shader which looks good on objects designed to look like the surface of electronic items such as a T.V. remote control."
}, {
    name: "CARBON FIBRE",
    img: ["carbonfibre.png"],
    file: "https://gumroad.com/l/rkqRS",
    size: 0.97,
    author: "Malicious Brews",
    blender: "2.8x",
    engine: "Cycles",
    pub: "July 14, 2020",
    lic: "CC0 1.0 Universal",
    desc: "Shader which tries to emulate the surface of carbon fibre sheets"
}, {
    name: "ROCK1",
    img: ["rock1.png"],
    file: "Rock1.blend",
    size: 7.30,
    author: "Luciano Marquez",
    blender: "2.8x",
    engine: "Cycles/Eevee",
    pub: "10 July, 2020",
    lic: "CC BY 2.0",
    desc: "Fantastic rock shader by Luciano Marquez."
}, {
    name: "BRICKS1",
    img: ["bricks1.png"],
    file: "https://gumroad.com/l/Brcks",
    size: 2.92,
    author: "Simon Thommes",
    blender: "2.8x",
    engine: "Cycles",
    pub: "16 July, 2020",
    lic: "CC BY 2.0",
    desc: "Realistic set of brick shaders by Simon Thommes."
}, {
    name: "BRICKS2",
    img: ["bricks2.png"],
    file: "https://gumroad.com/l/Brcks",
    size: 2.92,
    author: "Simon Thommes",
    blender: "2.8x",
    engine: "Cycles",
    pub: "16 July, 2020",
    lic: "CC BY 2.0",
    desc: "Realistic set of brick shaders by Simon Thommes."
}, {
    name: "BRICKS3",
    img: ["bricks3.png"],
    file: "https://gumroad.com/l/Brcks",
    size: 2.92,
    author: "Simon Thommes",
    blender: "2.8x",
    engine: "Cycles",
    pub: "16 July, 2020",
    lic: "CC BY 2.0",
    desc: "Realistic set of brick shaders by Simon Thommes."
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}];
