const materials = [{
    name: "PBR PLASTIC",
    img: ["pbrplastic.png"],
    file: "PBRPlastic.blend",
    size: 6.89,
    blender: "2.7x",
    engine: "Cycles",
    author: "Retrax",
    pub: "July 13, 2020",
    lic: "CC0 1.0 Universal",
    desc: "A simple PBR plastic shader."
}, {
    name: "CUTTING MAT",
    img: ["cuttingmat.png"],
    file: "CuttingMat.blend",
    size: 6.93,
    author: "Retrax",
    blender: "2.7x",
    engine: "Cycles",
    pub: "July 13, 2020",
    lic: "CC0 1.0 Universal",
    desc: "A shader designed to emulate the surface of a cutting mat which is often used in workshop."
}, {
    name: "FLANNEL",
    img: ["flannel.png"],
    file: "Flannel.blend",
    size: 7.00,
    author: "Nanoman",
    blender: "2.7x",
    engine: "Cycles",
    pub: "July 13, 2020",
    lic: "CC0 1.0 Universal",
    desc: "A shader designed to emulate the surface of flannel clothing."
}, {
    name: "GRAINY PLASTIC",
    img: ["grainyplastic.png"],
    file: "GrainyPlastic.blend",
    size: 6.89,
    author: "Retrax",
    blender: "2.7x",
    engine: "Cycles",
    pub: "July 14, 2020",
    lic: "CC0 1.0 Universal",
    desc: "A shader which looks good on objects designed to look like the surface of electronic items such as a T.V. remote control."
}, {
    name: "CARBON FIBRE",
    img: ["carbonfibre.png"],
    file: "carbonFibre.blend",
    size: 7.20,
    author: "Unknown",
    blender: "2.8x",
    engine: "Cycles",
    pub: "July 14, 2020",
    lic: "CC0 1.0 Universal",
    desc: "Shader which tries to emulate the surface of carbon fibre sheets"
}, {
    name: "ROCK1",
    img: ["rock1.png"],
    file: "Rock1.blend",
    size: 7.30,
    author: "Luciano Marquez",
    blender: "2.8x",
    engine: "Cycles/Eevee",
    pub: "10 July, 2020",
    lic: "CC BY 2.0",
    desc: "Fantastic rock shader by Luciano Marquez"
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    engine: "",
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}];
