const materials = [{
    name: "PBR PLASTIC",
    img: ["pbrplastic.png"],
    file: "PBRPlastic.blend",
    size: 6.89,
    blender: "2.79",
    render engine: Cycles,
    author: "Retrax",
    pub: "July 13, 2020",
    lic: "CC0 1.0 Universal",
    desc: "Lorem ipsum dolor sit amet consectour"
}, {
    name: "CUTTING MAT",
    img: ["cuttingmat.png"],
    file: "CuttingMat.blend",
    size: 6.93,
    author: "Retrax",
    blender: "2.79",
    render engine: Cycles,
    pub: "July 13, 2020",
    lic: "CC0 1.0 Universal",
    desc: ""
}, {
    name: "FLANNEL",
    img: ["flannel.png"],
    file: "Flannel.blend",
    size: 7.00,
    author: "Nanoman",
    blender: "2.79",
    render engine: Cycles,
    pub: "July 13, 2020",
    lic: "CC0 1.0 Universal",
    desc: ""
}, {
    name: "GRAINY PLASTIC",
    img: ["grainyplastic.png"],
    file: "GrainyPlastic.blend",
    size: 6.89,
    author: "Retrax",
    blender: "2.79",
    render engine: Cycles,
    pub: "July 14, 2020",
    lic: "CC0 1.0 Universal",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}, {
    name: "DEFAULT",
    img: ["default.png"],
    file: "",
    size: 0.00,
    author: "",
    blender: "0.0",
    render engine: blank,
    pub: "Januray 1, 1970",
    lic: "",
    desc: ""
}];
